package com.studyeasy.staticsynchronization;

/*Locks get applied based on object. static synchronization help to over come this drawback.*/

class Brackets{
	synchronized static public void generate(String threadCode) {
		for(int i=0;i<10;i++)
			if(i<5)
				System.out.print("[");
			else 
				System.out.print("]");
		System.out.println("Generated by :"+threadCode);
	}
	
}

public class App {

	public static void main(String[] args) {

		new Thread(new Runnable() {

			@Override
			public void run() {
				
				for(int i=1;i<=5;i++)
					Brackets.generate("Thread 1");
			}
			
		}).start();

		new Thread(new Runnable() {

			@Override
			public void run() {
				for(int i=1;i<=5;i++)
					Brackets.generate("Thread 2");
			}
			
		}).start();
	}

}
